In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [125]:
#Reading into pandas DataFrame
data=pd.read_csv('Assignment-Business-Quant.csv')

In [126]:
#Info about Data
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 210 entries, 0 to 209
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Category        210 non-null    object 
 1   Item            210 non-null    object 
 2   Year            210 non-null    int64  
 3   Sales           210 non-null    int64  
 4   Sales Growth %  0 non-null      float64
dtypes: float64(1), int64(2), object(2)
memory usage: 8.3+ KB


### Below Steps are for the Understanding of Data

In [127]:
data.head(15)

Category      Item  Year  Sales  Sales Growth %
0        Fruit     Apple  2015     90             NaN
1        Fruit     Apple  2016     41             NaN
2        Fruit     Apple  2017     71             NaN
3        Fruit     Apple  2018     59             NaN
4        Fruit     Apple  2019     41             NaN
5        Fruit     Apple  2010     25             NaN
6        Fruit     Apple  2011     75             NaN
7        Fruit     Apple  2012     62             NaN
8        Fruit     Apple  2013     96             NaN
9        Fruit     Apple  2014     39             NaN
10  Vegetables  Brocolli  2015     32             NaN
11  Vegetables  Brocolli  2016     17             NaN
12  Vegetables  Brocolli  2017     45             NaN
13  Vegetables  Brocolli  2018     44             NaN
14  Vegetables  Brocolli  2019     47             NaN

In [128]:
data['Category'].value_counts()

Fruit         60
Vegetables    60
Plants        30
Roots         30
Seeds         30
Name: Category, dtype: int64

In [129]:
data_copy=data.sort_values(by='Year')

In [130]:
#Sorting Values
data=data.sort_values(by=["Item",'Year'])

In [131]:
data=data.reset_index()

In [132]:
data.head(10)

index Category       Item  Year  Sales  Sales Growth %
0    190   Plants  Aloe Vera  2010     27             NaN
1    191   Plants  Aloe Vera  2011     31             NaN
2    192   Plants  Aloe Vera  2012     99             NaN
3    193   Plants  Aloe Vera  2013     10             NaN
4    194   Plants  Aloe Vera  2014     60             NaN
5    195   Plants  Aloe Vera  2015     31             NaN
6    196   Plants  Aloe Vera  2016     90             NaN
7    197   Plants  Aloe Vera  2017     87             NaN
8    198   Plants  Aloe Vera  2018     30             NaN
9    199   Plants  Aloe Vera  2019     43             NaN

In [133]:
data=data.drop(columns=['index'],axis=1)

In [216]:
#data['Item'].value_counts()

In [169]:
#Trying out the logic
(data[data['Year']==2012]['Sales'].values)-(data[data['Year']==2011]['Sales'].values)

array([ 68, -13,   0,  27, -44,  34,  -2,  49,  20, -18,  -8, -17, -37,
       -24,   4, -35,   3, -39,  17,  47,  23], dtype=int64)

In [215]:
(data[data_copy['Year']==2010]['Sales'].values)

array([ 27,  25,  65,  45,  35,  34,  14,  59,  61,  98,  23,  16,  74,
        10,  40,  57,  64,  80,  41,  93, 100], dtype=int64)

In [217]:
data.head(13)

Category       Item  Year  Sales  Sales Growth %  Sales Last Year
0    Plants  Aloe Vera  2010     27             NaN                0
1    Plants  Aloe Vera  2011     31             NaN                0
2    Plants  Aloe Vera  2012     99             NaN                0
3    Plants  Aloe Vera  2013     10             NaN                0
4    Plants  Aloe Vera  2014     60             NaN                0
5    Plants  Aloe Vera  2015     31             NaN                0
6    Plants  Aloe Vera  2016     90             NaN                0
7    Plants  Aloe Vera  2017     87             NaN                0
8    Plants  Aloe Vera  2018     30             NaN                0
9    Plants  Aloe Vera  2019     43             NaN                0
10    Fruit      Apple  2010     25             NaN                0
11    Fruit      Apple  2011     75             NaN                0
12    Fruit      Apple  2012     62             NaN                0

In [209]:
(data[data_copy['Year']==2011]['Sales'].values[0])

array([31, 75, 45, 26, 64, 47, 76, 41, 72, 68, 28, 39, 88, 78, 44, 68, 45,
       49, 51, 41, 72], dtype=int64)

In [182]:
data_copy=data_copy.drop(columns=['Sales Last Year'])

In [221]:
#Adding Sales last year Column
SLY=[]
first=True
c=0
for i in data_copy['Year']:
    if i==2010:
        SLY.append(0)
        if first==False:
            c=c+1
    elif i>2010:
        SLY.append((data[data_copy['Year']==i-1]['Sales'].values[c]))
        first=False

In [222]:
data['Sales Last Year']=SLY

In [224]:
data.head(15)

Category       Item  Year  Sales  Sales Growth %  Sales Last Year
0    Plants  Aloe Vera  2010     27             NaN                0
1    Plants  Aloe Vera  2011     31             NaN               27
2    Plants  Aloe Vera  2012     99             NaN               31
3    Plants  Aloe Vera  2013     10             NaN               99
4    Plants  Aloe Vera  2014     60             NaN               10
5    Plants  Aloe Vera  2015     31             NaN               60
6    Plants  Aloe Vera  2016     90             NaN               31
7    Plants  Aloe Vera  2017     87             NaN               90
8    Plants  Aloe Vera  2018     30             NaN               87
9    Plants  Aloe Vera  2019     43             NaN               30
10    Fruit      Apple  2010     25             NaN                0
11    Fruit      Apple  2011     75             NaN               25
12    Fruit      Apple  2012     62             NaN               75
13    Fruit      Apple  2013     96             NaN               62
14    Fruit      Apple  2014     39             NaN               96

In [263]:
#Formula for Sales Growth % = (Sales in current year/Sales in Last year)-1
#Adding Sales Growth Column
SG=[]
first=True
x=0
counter=1
for i in data['Year']:
    if counter==10:
        counter=0
        x=x+1
    if i==2010:
        SG.append(0)
        counter=+1
    elif i>2010:
        value=np.round((((data[data['Year']==i]['Sales'].values[x])/(data[data['Year']==i]['Sales Last Year'].values[x]))-1)*100,2)
        SG.append(value)
        counter=counter+1



In [265]:
data['Sales Growth %']=SG

In [268]:
data=data.drop(columns=['Sales Growth %','Sales Growth'])

In [269]:
data['Sales Growth %']=SG

In [270]:
data

Category       Item  Year  Sales  Sales Last Year  Sales Growth %
0     Plants  Aloe Vera  2010     27                0            0.00
1     Plants  Aloe Vera  2011     31               27           14.81
2     Plants  Aloe Vera  2012     99               31          219.35
3     Plants  Aloe Vera  2013     10               99          -89.90
4     Plants  Aloe Vera  2014     60               10          500.00
..       ...        ...   ...    ...              ...             ...
205   Plants     Tomato  2015     60               45           33.33
206   Plants     Tomato  2016     49               60          -18.33
207   Plants     Tomato  2017     10               49          -79.59
208   Plants     Tomato  2018     35               10          250.00
209   Plants     Tomato  2019     35               35            0.00

[210 rows x 6 columns]

In [242]:
data['Sales Growth']=SG

In [245]:
data.head(40)

Category       Item  Year  Sales  Sales Growth %  Sales Last Year  \
0       Plants  Aloe Vera  2010     27             NaN                0   
1       Plants  Aloe Vera  2011     31             NaN               27   
2       Plants  Aloe Vera  2012     99             NaN               31   
3       Plants  Aloe Vera  2013     10             NaN               99   
4       Plants  Aloe Vera  2014     60             NaN               10   
5       Plants  Aloe Vera  2015     31             NaN               60   
6       Plants  Aloe Vera  2016     90             NaN               31   
7       Plants  Aloe Vera  2017     87             NaN               90   
8       Plants  Aloe Vera  2018     30             NaN               87   
9       Plants  Aloe Vera  2019     43             NaN               30   
10       Fruit      Apple  2010     25             NaN                0   
11       Fruit      Apple  2011     75             NaN               25   
12       Fruit      Apple  2012     62             NaN               75   
13       Fruit      Apple  2013     96             NaN               62   
14       Fruit      Apple  2014     39             NaN               96   
15       Fruit      Apple  2015     90             NaN               39   
16       Fruit      Apple  2016     41             NaN               90   
17       Fruit      Apple  2017     71             NaN               41   
18       Fruit      Apple  2018     59             NaN               71   
19       Fruit      Apple  2019     41             NaN               59   
20  Vegetables  Asparagus  2010     65             NaN                0   
21  Vegetables  Asparagus  2011     45             NaN               65   
22  Vegetables  Asparagus  2012     45             NaN               45   
23  Vegetables  Asparagus  2013     46             NaN               45   
24  Vegetables  Asparagus  2014     80             NaN               46   
25  Vegetables  Asparagus  2015     95             NaN               80   
26  Vegetables  Asparagus  2016     31             NaN               95   
27  Vegetables  Asparagus  2017     82             NaN               31   
28  Vegetables  Asparagus  2018     85             NaN               82   
29  Vegetables  Asparagus  2019     46             NaN               85   
30       Fruit   Avocados  2010     45             NaN                0   
31       Fruit   Avocados  2011     26             NaN               45   
32       Fruit   Avocados  2012     53             NaN               26   
33       Fruit   Avocados  2013     41             NaN               53   
34       Fruit   Avocados  2014     42             NaN               41   
35       Fruit   Avocados  2015     50             NaN               42   
36       Fruit   Avocados  2016     63             NaN               50   
37       Fruit   Avocados  2017     15             NaN               63   
38       Fruit   Avocados  2018     71             NaN               15   
39       Fruit   Avocados  2019     61             NaN               71   

    Sales Growth  
0       0.000000  
1      14.814815  
2     219.354839  
3     -89.898990  
4     500.000000  
5     -48.333333  
6     190.322581  
7      -3.333333  
8     -65.517241  
9      43.333333  
10      0.000000  
11    200.000000  
12    -17.333333  
13     54.838710  
14    -59.375000  
15    130.769231  
16    -54.444444  
17     73.170732  
18    -16.901408  
19    -30.508475  
20      0.000000  
21    200.000000  
22      0.000000  
23      2.222222  
24     73.913043  
25     18.750000  
26    -67.368421  
27    164.516129  
28      3.658537  
29    -45.882353  
30      0.000000  
31    -30.769231  
32      0.000000  
33    -22.641509  
34      2.439024  
35     19.047619  
36     26.000000  
37    -76.190476  
38    373.333333  
39    -14.084507

In [272]:
data.to_csv('data')

In [276]:
data

Category       Item  Year  Sales  Sales Last Year  Sales Growth %
0     Plants  Aloe Vera  2010     27                0            0.00
1     Plants  Aloe Vera  2011     31               27           14.81
2     Plants  Aloe Vera  2012     99               31          219.35
3     Plants  Aloe Vera  2013     10               99          -89.90
4     Plants  Aloe Vera  2014     60               10          500.00
..       ...        ...   ...    ...              ...             ...
205   Plants     Tomato  2015     60               45           33.33
206   Plants     Tomato  2016     49               60          -18.33
207   Plants     Tomato  2017     10               49          -79.59
208   Plants     Tomato  2018     35               10          250.00
209   Plants     Tomato  2019     35               35            0.00

[210 rows x 6 columns]

In [278]:
#Dropping Category
data=data.drop(columns=['Category'])

In [283]:
data.to_csv('data')